/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import config.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lenovo
 */
public class jdwl_mk extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    jdwl_mkManager jdwl_mkManager;
    boolean sedangDiEdit = false;
    /**
     * Creates new form jdwl_mk
     */
    public jdwl_mk() {
        initComponents();
        jdwl_mkManager = new jdwl_mkManager();
        tampilDataTable();
    }
    
    private void tampilDataTable() {
        String[] kolom = {"ID", "Kode", "Mata Kuliah", "Hari", "Jam Mulai", "Jam Selesai", "Ruangan", "Dosen"};
        tableModel = new DefaultTableModel(null, kolom);
        for (jdwl_mkModel model : jdwl_mkManager.tampilSemua()) {
            String[] row = new String[kolom.length];
            row[0] = String.valueOf(model.getId());
            row[1] = model.getKode();
            row[2] = model.getMataKuliah();
            row[3] = model.getHari();
            row[4] = model.getJamMulai().toString();
            row[5] = model.getJamSelesai().toString();
            row[6] = model.getRuangan();
            row[7] = model.getDosen();
                                    
            tableModel.addRow(row);
        }
        tbl_jdwlmk.setModel(tableModel);
        tbl_jdwlmk.clearSelection();
    }
    
    private void refresh(){
        tampilDataTable();
        clearData();
        sedangDiEdit = false;
    }
    
    private void clearData() {
        txt_kode.setText("");
        txt_mk.setText("");
        txt_hari.setText("");
        txt_jm.setText("");
        txt_js.setText("");
        txt_ruangan.setText("");
        txt_dosen.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jdwlmk = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        txt_mk = new javax.swing.JTextField();
        txt_hari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_jm = new javax.swing.JTextField();
        txt_js = new javax.swing.JTextField();
        txt_ruangan = new javax.swing.JTextField();
        txt_dosen = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Jadwal Mata Kuliah");

        tbl_jdwlmk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tbl_jdwlmk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_jdwlmkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_jdwlmk);
        if (tbl_jdwlmk.getColumnModel().getColumnCount() > 0) {
            tbl_jdwlmk.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Kode");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mata Kuliah");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Hari");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jam Mulai");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Jam Selesai");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Ruangan");

        txt_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kodeActionPerformed(evt);
            }
        });

        txt_mk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mkActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Dosen");

        refresh.setText("Refresh");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_js, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_jm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hari, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(203, 203, 203)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_dosen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(txt_mk, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout)
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(refresh)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(hapus)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_jm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(logout)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_js, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(simpan)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_ruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(kembali)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_dosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeActionPerformed

    private void txt_mkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mkActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        dashboard dashboard = new dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
        String kode = txt_kode.getText();
        String matakuliah = txt_mk.getText();
        String hari = txt_hari.getText();
        String jam_mulai = txt_jm.getText();
        String jam_selesai = txt_js.getText();
        String ruangan = txt_ruangan.getText();
        String dosen = txt_dosen.getText();

        if (!kode.isEmpty() && !matakuliah.isEmpty() && !hari.isEmpty() && !jam_mulai.isEmpty() && !jam_selesai.isEmpty()
                && !ruangan.isEmpty() && !dosen.isEmpty()) {
            if (sedangDiEdit) {
                String id = (String) tbl_jdwlmk.getValueAt(tbl_jdwlmk.getSelectedRow(), 0);
                Time JamMulai = Time.valueOf(jam_mulai);
                Time JamSelesai = Time.valueOf(jam_selesai);

                jdwl_mkManager.update(kode, matakuliah, hari, JamMulai, JamSelesai, ruangan, dosen, Integer.valueOf(id));
            } else {
                Time JamMulai = Time.valueOf(jam_mulai);
                Time JamSelesai = Time.valueOf(jam_selesai);

                jdwl_mkManager.insert(kode, matakuliah, hari, JamMulai, JamSelesai, ruangan, dosen);
            }
            tampilDataTable();
            clearData();
            sedangDiEdit = false;
        } else {
            JOptionPane.showMessageDialog(null, "Tidak boleh ada yang kosong !");
        }
    }//GEN-LAST:event_simpanMouseClicked

    private void tbl_jdwlmkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_jdwlmkMouseClicked
        // TODO add your handling code here:
        sedangDiEdit = true;
        String id = (String) tbl_jdwlmk.getValueAt(tbl_jdwlmk.getSelectedRow(), 0);
        jdwl_mkModel model = jdwl_mkManager.byId(Integer.valueOf(id));
        txt_kode.setText(model.getKode());
        txt_mk.setText(model.getMataKuliah());
        txt_hari.setText(model.getHari());
        txt_jm.setText(model.getJamMulai().toString());
        txt_js.setText(model.getJamSelesai().toString());
        txt_ruangan.setText(model.getRuangan());
        txt_dosen.setText(model.getDosen());
    }//GEN-LAST:event_tbl_jdwlmkMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        if(sedangDiEdit){
            String id = (String) tbl_jdwlmk.getValueAt(tbl_jdwlmk.getSelectedRow(), 0);
            jdwl_mkManager.delete(id);
            refresh();
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdwl_mk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdwl_mk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdwl_mk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdwl_mk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jdwl_mk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton logout;
    private javax.swing.JButton refresh;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tbl_jdwlmk;
    private javax.swing.JTextField txt_dosen;
    private javax.swing.JTextField txt_hari;
    private javax.swing.JTextField txt_jm;
    private javax.swing.JTextField txt_js;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_mk;
    private javax.swing.JTextField txt_ruangan;
    // End of variables declaration//GEN-END:variables

    public class jdwl_mkModel{
        private int id;
        private String kode;
        private String matakuliah;
        private String hari;
        private Time jam_mulai;
        private Time jam_selesai;
        private String ruangan;
        private String dosen;

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

        public String getKode() {
            return kode;
        }

        public void setKode(String kode) {
            this.kode = kode;
        }

        public String getMataKuliah() {
            return matakuliah;
        }

        public void setMataKuliah(String matakuliah) {
            this.matakuliah = matakuliah;
        }

        public String getHari() {
            return hari;
        }

        public void setHari(String hari) {
            this.hari = hari;
        }

        public Time getJamMulai() {
            return jam_mulai;
        }

        public void setJamMulai(Time jam_mulai) {
            this.jam_mulai = jam_mulai;
        }

        public Time getJamSelesai() {
            return jam_selesai;
        }

        public void setJamSelesai(Time jam_selesai) {
            this.jam_selesai = jam_selesai;
        }
        
        public String getRuangan() {
            return ruangan;
        }

        public void setRuangan(String ruangan) {
            this.ruangan = ruangan;
        }
        
        public String getDosen() {
            return dosen;
        }

        public void setDosen(String dosen) {
            this.dosen = dosen;
        }
        
    }
    
    public class jdwl_mkManager{
        private final Connection koneksiDatabase;

        public jdwl_mkManager() {
        this.koneksiDatabase = koneksi.koneksiDB();
        }
    
        public List<jdwl_mkModel> tampilSemua() {
        String namaTable = "tbl_jadwal";
        String query = "SELECT * FROM " + namaTable;
        jdwl_mkModel model;
        List<jdwl_mkModel> list = new ArrayList<>();

        try (PreparedStatement preparedStatement = koneksiDatabase.prepareStatement(query)) {
            ResultSet hasilQuery = preparedStatement.executeQuery();

            while (hasilQuery.next()) {
                model = new jdwl_mkModel();
                model.setId(hasilQuery.getInt("id"));
                model.setKode(hasilQuery.getString("kode"));
                model.setMataKuliah(hasilQuery.getString("matakuliah"));
                model.setHari(hasilQuery.getString("hari"));
                model.setJamMulai(hasilQuery.getTime("jam_mulai"));
                model.setJamSelesai(hasilQuery.getTime("jam_selesai"));
                model.setRuangan(hasilQuery.getString("ruangan"));
                model.setDosen(hasilQuery.getString("dosen"));
                list.add(model);
            }
            return list;
        } catch (SQLException ex) {
            ex.printStackTrace();
            return null;
        }
    }


        public jdwl_mkModel byId(int id){
        String namaTable = "tbl_jadwal";
        String query = "SELECT * FROM " + namaTable + " WHERE id = ?";
        jdwl_mkModel model = null;

        try (PreparedStatement preparedStatement = koneksiDatabase.prepareStatement(query)) {
            preparedStatement.setInt(1, id);
            ResultSet hasilQuery = preparedStatement.executeQuery();

            while (hasilQuery.next()) {
                model = new jdwl_mkModel();
                model.setId(hasilQuery.getInt("id"));
                model.setKode(hasilQuery.getString("kode"));
                model.setMataKuliah(hasilQuery.getString("matakuliah"));
                model.setHari(hasilQuery.getString("hari"));
                model.setJamMulai(hasilQuery.getTime("jam_mulai"));
                model.setJamSelesai(hasilQuery.getTime("jam_selesai"));
                model.setRuangan(hasilQuery.getString("ruangan"));
                model.setDosen(hasilQuery.getString("dosen"));
            }            
            return model;
        } catch (SQLException ex) {
            ex.printStackTrace();
            return null;
        }
    }


        public boolean insert(String kode, String matakuliah, String hari, Time jam_mulai, Time jam_selesai, String ruangan, String dosen) {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_kelas", "root", "")) {
            String query = "INSERT INTO tbl_jadwal (kode, matakuliah, hari, jam_mulai, jam_selesai, ruangan, dosen) VALUES (?, ?, ?, ?, ?, ?, ?)";

            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, kode);
                preparedStatement.setString(2, matakuliah);
                preparedStatement.setString(3, hari);
                preparedStatement.setTime(4, jam_mulai);
                preparedStatement.setTime(5, jam_selesai);
                preparedStatement.setString(6, ruangan);
                preparedStatement.setString(7, dosen);


                preparedStatement.executeUpdate();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }

        public boolean update(String kode, String matakuliah, String hari, Time jam_mulai, Time jam_selesai, String ruangan, String dosen, int id) {
        String namaTable = "tbl_jadwal";
        String query = "UPDATE " + namaTable + " SET `kode`=?, `matakuliah`=?, `hari`=?, `jam_mulai`=?, `jam_selesai`=?, `ruangan`=?, `dosen`=? WHERE  `id`=?";

        try {
            PreparedStatement preparedStatement = koneksiDatabase.prepareStatement(query);
            preparedStatement.setString(1, kode);
            preparedStatement.setString(2, matakuliah);
            preparedStatement.setString(3, hari);
            preparedStatement.setTime(4, jam_mulai);
            preparedStatement.setTime(5, jam_selesai);
            preparedStatement.setString(6, ruangan);
            preparedStatement.setString(7, dosen);
            preparedStatement.setInt(8, id);

            preparedStatement.executeUpdate();
            return true;
        } catch (SQLException ex) {
            ex.printStackTrace();
            return false;
        }
    }


        public boolean delete(String id) {
        String namaTable = "tbl_jadwal";
            String query = "DELETE FROM "+namaTable+" WHERE id = "+id;

            try {
                PreparedStatement preparedStatement = koneksiDatabase.prepareStatement(query);
                preparedStatement.execute();   
                return true;
            } catch (SQLException ex) {
            ex.printStackTrace();
            return false;
            }
        }
    }
}